spring.datasource.url=jdbc:mysql://proddb:3306/csm_prod
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none

server.port=8080
auth.client.secret=v1oByfnxH2xE1A5rwCqgGp6AyTtsjxgCOn2wCw6unFI=

server.address=0.0.0.0

auth.host=http://auth-api-prod:8080/auth