spring.application.name=Customer Supplier Management

#spring.profiles.active = local

spring.datasource.url=jdbc:mysql://localhost:3306/csmdb
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.sql.init.mode=always


server.port=8081

auth.mock.local=false

auth.host=http://192.168.1.100/auth
auth.login.url=/api/v1/login
auth.register.url=/api/v1/register
auth.validateToken.url=/api/v1/validate/token
auth.getUsers.url=/api/v1/users/get
auth.deleteUser.url=/api/v1/user/deactivate/{userId}
auth.searchUsers.url=/api/v1/users/search
auth.get_user_detail.url=/api/v1/get/user/detail
auth.change_password.url=/api/v1/password/change

auth.client.name=CSM
auth.client.secret=v1oByfnxH2xE1A5rwCqgGp6AyTtsjxgCOn2wCw6unFI=

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [requestId=%X{requestId}] [%thread] %-5level %logger{36} - %msg%n

